

LOCK TABLES `clients` WRITE;
/*!40000 ALTER TABLE `clients` DISABLE KEYS */;
INSERT INTO `clients` (`id`, `nom`)
VALUES
    (1, 'ENGEN'),
    (2, 'OILIBYA'),
    (3, 'PETRO GABON'),
    (4, 'TOTAL'),
    (5, 'PIZO');

/*!40000 ALTER TABLE `clients` ENABLE KEYS */;
UNLOCK TABLES;


INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESEL 600 SUPER 15W40','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESEL 600 SUPER 15W40','C4X5L','18','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESEL 600 SUPER 15W40','C4X5L','18','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESEL 600 SUPER 15W40','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESEL 500 SUPER 15W40','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN XTREME 15W40','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN XTREME 15W40','C4X5L','18','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN XTREME 15W40','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER 20W50','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER 20W50','C6X4L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER 20W50','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PROTECTA HI-MILEAGE 20W50','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PROTECTA HI-MILEAGE 20W50','C6X4L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PROTECTA HI-MILEAGE 20W50','C4X5L','18','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PROTECTA HI-MILEAGE 20W50','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PREMIUM MOTOR OIL 40','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PREMIUM MOTOR OIL 40','C4X5L','18','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN PREMIUM MOTOR OIL 40','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESELUBE 540','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESELUBE 530','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN DIESELUBE 510','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN AGRIFLUID ','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ATF 22D','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEARLUBE HP 80W-A','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEARLUBE HP 80W90','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEARLUBE EP 80W90','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEARLUBE EP 80W90','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEARLUBE EP 85W140','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TRANSFLUID TO-4 SAE 50','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER OUTBOARD TC-W3','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER OUTBOARD TC-W3','C4X5L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER OUTBOARD TC-W3','C6X4L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN SUPER OUTBOARD TC-W3','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TWO STROKE SELFMIX','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TWO STROKE SELFMIX','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TWO STROKE SUPER','C24X1L','21.6','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TWO STROKE SUPER','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TQH 10/46','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TQH 10/68','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TQH 20/32','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TQH 20/46','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TQH 20/68','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ENGEN TQH 20/100','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 68','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 100','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 150','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 220','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 320','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 460','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 680','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENGEAR 1000','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GENCYL 460','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRONAS GEO S 40','FUTS','185','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HUILE DECLASSEE','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('POWEROIL TO 1020','FUTS','180','1');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ACCEL ULTRA 20W50','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ACCEL ULTRA 20W50','C24X1L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ACCEL ULTRA 20W50','C6X4L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ACCEL XL10  20W50','C12X1L','10.8','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ACCEL XL10  20W50','C4X5L','18','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX HD 10W','FUTS','180','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX HD 30','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX DM5 SAE 40','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX HD 40','C24X1L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX HD 40','C6X4L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX HD 50','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX DM12 15W40','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX SHP 15W40','C24X1L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX SHP 15W40','C6X4L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX DM 5 SAE 40','C12X1L','18','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX DM 5 SAE 40','C4X5L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX DM 12 15W40','C12X1L','10.8','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DEOMAX DM 12 15W40','C4X5L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DIESEL SAFARI OIL 40','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('DIESEL SAFARI OIL 40','VRAC','1','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEAR OIL HD  80W90   GL-4','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEAR OIL 80W90          GL-5','C24X1L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEAR OIL XHD  80W90   ','C12X1L','10.8','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEAR OIL XHD  80W90   ','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEAR OIL 85W140','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('GEAR OIL XHD 85W140','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HP 300A MOTOR OIL 40','C6X4L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HYDROL HTE 32','FUTS','180','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HYDROL 46','FUTS','180','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HYDROL 68','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HYDROL 100','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('MARINEGARD 312','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('MARINEGARD 412','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('MARINEGARD 570','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('QUEST 2T','FUTS','180','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('QUEST 2T','C12X1L','10.8','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('RED FLUSH OIL','FUTS','180','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('THERMIC OIL','FUTS','180','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TORQGEAR XP 68','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TORQGEAR XP 100','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TORQGEAR XP 150','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TORQGEAR XP 220','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TORQGEAR XP 320','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TORQGEAR XP 460','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TRANS FD 50','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('SAFARI OIL 40','C24X1L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('SAFARI OIL 40','C6X4L','21.6','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('SAFARI OIL 40','FUTS','185','2');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HUILE DECLASSEE','Fûts','180','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO  MOTEUR 10W','Futs','180','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO OKAN DRIVER 40','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO MOTEUR 50','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO DIESEL 15W40','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO  DIESEL SUPER 15W40','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO HYDRAULIQUE 32','Futs','180','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO HYDRAULIQUE 46','Futs','180','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO HYDRAULIQUE 68','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO HYDRAULIQUE 100','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO TRANSMISSION 80W90','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO TRANSMISSION 85W140','Fûts','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('HUILE THERMIQUE','Futs','180','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO ENGRENAGE 150','Futs','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO ENGRENAGE 220','Futs','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO ENGRENAGE 320','Futs','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO ENGRENAGE 460','Futs','185','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PETRO OKAN OUTBOARD 2T','Futs','180','3');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO ATF 22D','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO 15W40 CI-4','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO HYDRAULIQUE 68 HM','Futs','180','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO TRANSMISSION 80W90 GL-5','Futs','180','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO TRANSMISSION 85W140 GL-5','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO MOTEUR 10W','Futs','180','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO HUILE DE CHAINE','Futs','180','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO ENGRENAGES 460','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('SIVVA SAE 40','C4*5L','18','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('SIVVA SAE 40','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('ATF DEXRON II','Futs','180','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO 2T TCW','Futs','180','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('PIZO MOTEUR DIESEL 15W40','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('APC MOTEUR DIESEL 15W40','Futs','185','5');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL 2 TEMPS Z','C122T','21.6','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  2  TEMPS Z','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL ATF 22 D','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  22','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  32','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  46','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  68','B20L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  68','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  100','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  AZOLLA  ZS  150','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER EP 68','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER EP 100','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER EP 150','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER EP 220','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER EP 320','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER EP 460','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER  EP  680','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER  EP  1000','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  CARTER  EP  3000','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  FLUID II D','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL DYNATRANS AC 30','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL DYNATRANS AC 50','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL DYNATRANS AC 50','VRAC','1','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EP  80W85','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EP  80W90','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EPB  85W90','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EQUIVIS ZS 32','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EQUIVIS  ZS  46','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EQUIVIS  ZS  68','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  EQUIVIS  ZS  100','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL MOTOR OIL SAE 40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL MOTOR OIL SAE 40','C20X1L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL MOTOR OIL SAE 40','C6X5L','27','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL MOTOR OIL SAE 40','VRAC','900','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL NATERIA MH 40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL NATERIA V 40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL NEPTUNA SUPER 2T SPORT','C20X1L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL NEPTUNA SUPER 2T SPORT','C12X2L','21.6','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL NEPTUNA SUPER 2T SPORT','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL PNEUMA 100','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  QUARTZ  5000  SAE  20W50','C20X1L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  QUARTZ  5000  SAE  20W50','C6X5L','27','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  QUARTZ  5000  SAE  20W50','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  G13  ','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  10W','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  10W','VRAC','4400','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  30','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  40','C20X1L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  40','C6X5L','27','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  S  50','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  4400 15W40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  4400 15W40','C20X1L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  4400 15W40','C6X5L','27','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA  TIR  7400  15W40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  RUBIA FLEET HD 300  15W40','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SERIOLA  1510','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SERIOLA  1510','VRAC','0','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SERIOLA ETA 100','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SPECIALE PIROGUE','C20X1L','18','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SPECIALE PIROGUE','C12X2L','21.6','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SPECIALE PIROGUE','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  SPECIALE CHAINE','FUTS','180','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  TOTALSOL','FUTS','170','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  TRANSMIS. TM  80W90','C12X2L','21.6','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  TRANSMIS. TM  80W90','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  TRANSMIS. TM  85W90','FUTS','185','4');
INSERT INTO produit_finis (nom,conditionnement,poids_emballage,client_id) VALUES ('TOTAL  TRANSMIS. TM  85W140','FUTS','185','4');